
name: LinkedIn Data Pipeline

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes (for follower fetch)
  workflow_dispatch:  # allow manual trigger

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 schedule supabase

      - name: Run LinkedIn data pipeline
        env:
          SCRAPINGDOG_API_KEY: ${{ secrets.SCRAPINGDOG_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python main.py
