name: LinkedIn Data Scraper

on:
  schedule:
    # Run every 4 hours
    - cron: '0 */4 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Clear pip cache
      run: |
        pip cache purge
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        
    - name: Run LinkedIn Scraper
      env:
        SCRAPINGDOG_API_KEY: ${{ secrets.SCRAPINGDOG_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python main.py
      
    - name: Upload CSV files as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linkedin-data
        path: |
          *.csv
        retention-days: 30
        
    - name: Commit and push data updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.csv
        timestamp=$(date -u)
        git commit -m "Update LinkedIn data: ${timestamp}" || exit 0
        git push
